# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginCompiler
                                 A QGIS plugin
 Help to compile .qrc and .ui files and help for make the translation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Cyprien Antignac
        email                : antignac.cyprien+git@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QTreeWidgetItem
# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the DockWidget
from .plugin_compiler_dockwidget import PluginCompilerDockWidget

# Import necessary module
import glob
import os
import subprocess
import datetime
from qgis.utils import plugins, pluginDirectory
from pyplugin_installer import installer as plugin_installer


class PluginCompiler:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PluginCompiler_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Plugin Compiler')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'PluginCompiler')
        self.toolbar.setObjectName(u'PluginCompiler')

        # print "** INITIALIZING PluginCompiler"

        self.pluginIsActive = False
        self.dockwidget = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PluginCompiler', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/plugin_compiler/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Plugin Compiler'),
            callback=self.run,
            parent=self.iface.mainWindow())

    # --------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        # print "** CLOSING PluginCompiler"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        # print "** UNLOAD PluginCompiler"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Plugin Compiler'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    # --------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            # print "** STARTING PluginCompiler"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget is None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = PluginCompilerDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

            self.cmbPluginList = self.dockwidget.cmbPluginList
            self.twGraphFile = self.dockwidget.twGraphFile
            self.twTranslateFile = self.dockwidget.twTranslateFile
            self.ckbQrc = self.dockwidget.ckbQrc
            self.ckbUi = self.dockwidget.ckbUi
            self.ckbPro = self.dockwidget.ckbPro
            self.ckbQm = self.dockwidget.ckbQm
            self.ckbTs = self.dockwidget.ckbTs

            process = self.dockwidget.btnExec
            process.clicked.connect(self.get_selected_leaves)

            self.ckbQrc.stateChanged.connect(self.current_plugin)
            self.ckbUi.stateChanged.connect(self.current_plugin)
            self.ckbPro.stateChanged.connect(self.current_plugin)
            self.ckbQm.stateChanged.connect(self.current_plugin)
            self.ckbTs.stateChanged.connect(self.current_plugin)

            plugins_list = sorted(plugins.keys(), key=str.casefold)
            for plugin in plugins_list:
                try:
                    icon = QIcon(plugin_installer.plugins.all()[plugin]['icon'])
                except KeyError:
                    icon = QIcon()
                self.cmbPluginList.addItem(icon, plugin)

            self.cmbPluginList.currentTextChanged.connect(self.current_plugin)
            self.current_plugin()

    def current_plugin(self):
        """
        Prepare the dockwidget for the select plugin
        """

        current_plugin = self.cmbPluginList.currentText()
        startpath = pluginDirectory(current_plugin)

        self.twGraphFile.clear()
        self.twTranslateFile.clear()

        check_graph = {".qrc": self.ckbQrc.isChecked(), ".ui": self.ckbUi.isChecked()}
        self.load_project_structure(startpath, self.twGraphFile, check_graph)

        check_trad = {".pro": self.ckbPro.isChecked(), ".qm": self.ckbQm.isChecked(), ".ts": self.ckbTs.isChecked()}
        self.load_project_structure(startpath, self.twTranslateFile, check_trad)

    def load_project_structure(self, startpath, tree, check_file):
        """
        Load Project tree structure in TreeWidget
        Based on solution of Softmixt : https://stackoverflow.com/questions/5144830/how-to-create-folder-view-in-pyqt-inside-main-window

        :param startpath: Path of the plugin
        :type startpath: str

        :param tree: QTreeWidget element where to display the folder and file architecture
        :type tree: QTreeWidget

        :param check_file: Dict of extension user choose to see
        :type check_file: dict
        """

        # List of ignore file or folder to make the tree
        list_ignore = ["__pycache__"]

        # Process all file and folder of startpath
        for element in os.listdir(startpath):

            # Add element to the list_ignore - exemple folder .git or file .gitignore
            if element.startswith("."):
                list_ignore.append(element)
            if element in list_ignore:
                pass

            else:
                # Make the system path
                path_info = startpath + "/" + element

                # Avoid add folder in tree if it already exist
                already_pass = []

                # If current element is detected as folder
                if os.path.isdir(path_info):
                    # If checkbox of file extension is check (shape = True) we display folder if it's extension format
                    for extension, shape in check_file.items():
                        if shape:
                            text = glob.glob(path_info + "/**/*{}".format(extension), recursive=True)
                            if len(text) > 0 and path_info not in already_pass:
                                already_pass.append(path_info)
                                # Call is_folder function
                                self.is_folder(tree, [os.path.basename(element)], path_info, check_file)

                    # If no checkbox are check then we display all folder
                    if not any(check_file.values()):
                        # Call is_folder function
                        self.is_folder(tree, [os.path.basename(element)], path_info, check_file)

                else:
                    value = os.path.basename(element)
                    # If checkbox of file extension is check (shape = True) we display file if it's extension format
                    for extension, shape in check_file.items():
                        if shape:
                            if value.endswith(extension):
                                # Call is_file function
                                self.is_file(tree, [value])

                    # If no checkbox are check then we display all file
                    if not any(check_file.values()):
                        # Call is_file function
                        self.is_file(tree, [value])

    def is_folder(self, tree, tree_element, path_info, check_file):
        """
        Add folder to the tree structure in QTreeWidget

        :param tree: QTreeWidget element where to display the folder and file architecture
        :type tree: QTreeWidget

        :param tree_element: Current element in the os.listdir(startpath)
        :type tree_element: list

        :param path_info: Path of the current element in the os.listdir(startpath)
        :type path_info: str

        :param check_file: Dict of extension user choose to see
        :type check_file: dict
        """

        parent_itm = QTreeWidgetItem(tree, tree_element)
        self.load_project_structure(path_info, parent_itm, check_file)
        parent_itm.setIcon(0, QIcon(':/plugins/plugin_compiler/icons/mIconFolder.png'))

    def is_file(self, tree, tree_element):
        """
        Add file to the tree structure in QTreeWidget

        :param tree: QTreeWidget element where to display the folder and file architecture
        :type tree: QTreeWidget

        :param tree_element: Current element in the os.listdir(startpath)
        :type tree_element: list
        """

        parent_itm = QTreeWidgetItem(tree, tree_element)
        parent_itm.setCheckState(0, Qt.Unchecked)
        # parent_itm.setIcon(0, QIcon(':/plugins/plugin_compiler/icons/mIconFile.png'))

    def get_selected_leaves(self):
        """
        Get the list of selected files in the QTreeWidget
        Based on solution of hollebread : https://stackoverflow.com/questions/26963786/pyqt-get-list-of-all-checked-in-qtreewidget

        :param startpath:
        :type startpath:

        :return:
        """

        checked_items = []

        def recurse(parent_item):
            for i in range(parent_item.childCount()):
                child = parent_item.child(i)
                grand_children = child.childCount()
                if grand_children > 0:
                    recurse(child)
                else:
                    if child.checkState(0) == Qt.Checked:
                        checked_items.append(child.text(0))

        recurse(self.twGraphFile.invisibleRootItem())
        print(checked_items)


def compile_ui_qrc():
    # Compile .ui files
    # ui_files = glob.glob('*.ui')
    # for ui in ui_files:
    #     (name, ext) = os.path.splitext(ui)
    #     print ("pyuic5.bat -o {}.py {}".format(name, ui))
    #     subprocess.call(["pyuic5.bat", "-o", "{}.py".format(name), ui])

    # Compile .qrc ressources file
    rc_files = glob.glob('*.qrc')
    for rc in rc_files:
        (name, ext) = os.path.splitext(rc)
        print("pyrcc5.bat -o {}.py {}".format(name, rc))
        subprocess.call(["pyrcc5.bat", "-o", "{}.py".format(name), rc])


def convert_pro():
    # Creation of .ts files from .pro file
    if not glob.glob('*.pro'):
        # Find the plugin class name
        plugin_dir = os.getcwd()
        f = open("{}/__init__.py".format(plugin_dir), "r")
        init_file = f.read()
        f.close()
        class_name = ""
        for line in init_file.split("\n"):
            if "return" in line:
                start = line.find("return") + len("return")
                end = line.find("(iface)")
                class_name = line[start + 1:end]

        # Find all .ui files
        ui_files = glob.glob("{}/**/*.ui".format(plugin_dir), recursive=True)
        str_pro_ui = ""
        for ui in ui_files:
            pro_ui = ui.replace(plugin_dir, " ..")
            str_pro_ui += pro_ui

        # Find all .py files
        py_files = glob.glob("{}/**/*.py".format(plugin_dir), recursive=True)
        str_pro_py = ""
        list_ignore_py = [" ..\\compile.py", " ..\\resources.py", " ..\\__init__.py"]
        for py in py_files:
            pro_py = py.replace(plugin_dir, " ..")
            str_pro_py += pro_py
            if "_dialog.py" in pro_py:
                list_ignore_py.append(pro_py)

        for ignore in list_ignore_py:
            str_pro_py = str_pro_py.replace(ignore, "")

        if str_pro_ui != "" and str_pro_py != "" and class_name != "":
            pro_string = "FORMS ={} \nSOURCES ={} \nTRANSLATIONS = {}_fr.ts".format(str_pro_ui, str_pro_py, class_name)
            f = open("{}/i18n/{}.pro".format(plugin_dir, class_name), "w")
            f.write(pro_string)
            f.close()
        else:
            print("Error")
    else:
        pass

    pro_files = glob.glob('i18n/*.pro')
    for pro in pro_files:
        print("pylupdate5.bat {}".format(pro))
        subprocess.call(["pylupdate5.bat"])
        subprocess.call(["pylupdate5.bat", "{}".format(pro)])


def convert_ts():
    # If translation is done, create .qm files from the .ts files
    pro_files = glob.glob('i18n/*.pro')
    ts_files = glob.glob('i18n/*.ts')
    pro_mtime = os.path.getmtime(pro_files[0])
    ts_mtime = os.path.getmtime(ts_files[0])
    print(ts_mtime - pro_mtime)
    print(datetime.datetime.fromtimestamp(pro_mtime))

    qm_files = glob.glob('i18n/*.ts')
    for qm in qm_files:
        print("lrelease {}".format(qm))
        subprocess.call(["lrelease", "{}".format(qm)])
